// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/trabajadores": {
            "get": {
                "tags": [
                    "trabajadores"
                ],
                "summary": "Listar todos los trabajadores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Trabajador"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "trabajadores"
                ],
                "summary": "Crear trabajador",
                "parameters": [
                    {
                        "description": "Datos",
                        "name": "trabajador",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Trabajador"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Trabajador"
                        }
                    }
                }
            }
        },
        "/trabajadores/{id}": {
            "put": {
                "tags": [
                    "trabajadores"
                ],
                "summary": "Actualizar trabajador",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos",
                        "name": "trabajador",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Trabajador"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "tags": [
                    "trabajadores"
                ],
                "summary": "Eliminar trabajador por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del trabajador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Eliminado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Trabajador": {
            "type": "object",
            "properties": {
                "apellido": {
                    "type": "string",
                    "example": "Vargas"
                },
                "cargo": {
                    "type": "string",
                    "example": "Developer"
                },
                "ci": {
                    "type": "string",
                    "example": "1234567"
                },
                "departamento": {
                    "type": "string",
                    "example": "Sistemas"
                },
                "id": {
                    "type": "string",
                    "example": "65f1c..."
                },
                "nombre": {
                    "type": "string",
                    "example": "Isaac"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Trabajadores USFX",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
